"""
CareerMind AI – Report Generator
Usage:
  python generateReport.py <json_string> <output_pdf> <output_png>
"""

import sys, json, textwrap, os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame,
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.colors import HexColor
from PIL import Image, ImageDraw, ImageFont

# ── COLOURS ──────────────────────────────────────────────────────────────
C_BLACK      = HexColor("#1A1A1A")
C_DARK_GRAY  = HexColor("#4A4A4A")
C_MID_GRAY   = HexColor("#787878")
C_LIGHT_GRAY = HexColor("#F2F2F2")
C_WHITE      = colors.white
C_ACCENT     = HexColor("#1A3A5C")
C_ACCENT2    = HexColor("#2E6DA4")
C_BORDER     = HexColor("#CCCCCC")
C_GREEN      = HexColor("#2D6A4F")
C_ORANGE     = HexColor("#C25B00")

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm


# ═════════════════════════════════════════════════════════════════════════
#  PDF GENERATOR
# ═════════════════════════════════════════════════════════════════════════

def draw_header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # Header bar
    canvas.setFillColor(C_ACCENT)
    canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, h - 10*mm, "CAREERMIND AI")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#A8C4E0"))
    canvas.drawString(MARGIN, h - 15*mm, "Personality Assessment Report")
    canvas.drawRightString(w - MARGIN, h - 12.5*mm, "careermind.app")
    # Footer bar
    canvas.setFillColor(C_ACCENT)
    canvas.rect(0, 0, w, 10*mm, fill=1, stroke=0)
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(HexColor("#A8C4E0"))
    canvas.drawCentredString(w/2, 3.5*mm,
        "Generated by CareerMind AI   |   careermind.app   |   Discover your personality, find your career path")
    canvas.setFont("Helvetica-Bold", 7)
    canvas.setFillColor(colors.white)
    canvas.drawRightString(w - MARGIN, 3.5*mm, f"Page {doc.page}")
    canvas.restoreState()


def ps(name, fontName="Helvetica", fontSize=9, textColor=None, leading=None,
       alignment=TA_LEFT, leftIndent=0, bold=False):
    if bold:
        fontName = "Helvetica-Bold"
    if textColor is None:
        textColor = C_DARK_GRAY
    if leading is None:
        leading = fontSize * 1.4
    return ParagraphStyle(name, fontName=fontName, fontSize=fontSize,
                          textColor=textColor, leading=leading,
                          alignment=alignment, leftIndent=leftIndent)


def section_bar(title, cw):
    t = Table([[Paragraph(title, ps("sh", fontName="Helvetica-Bold", fontSize=7,
                                     textColor=colors.white, leading=9))]],
              colWidths=[cw])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), C_ACCENT),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
    ]))
    return t


def generate_pdf(result, output_path):
    cw = PAGE_W - 2*MARGIN
    story = []

    # ── Identity block ──────────────────────────────────────────────────
    id_table = Table(
        [[[Paragraph(result["personality_type"],
                     ps("tc", fontName="Helvetica-Bold", fontSize=38,
                         textColor=C_ACCENT, leading=42))],
          [Spacer(1, 6*mm),
           Paragraph(result["personality_name"],
                     ps("tn", fontName="Helvetica-Bold", fontSize=17,
                         textColor=C_BLACK, leading=22)),
           Paragraph("MBTI Personality Type",
                     ps("tl", fontSize=7.5, textColor=C_MID_GRAY, leading=10))]]],
        colWidths=[45*mm, cw - 45*mm]
    )
    id_table.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), C_LIGHT_GRAY),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        ("LEFTPADDING",   (0,0),(-1,-1), 10),
        ("TOPPADDING",    (0,0),(-1,-1), 6),
        ("BOTTOMPADDING", (0,0),(-1,-1), 6),
        ("LINEAFTER",     (0,0),(0,0), 1, C_BORDER),
    ]))
    story += [id_table, Spacer(1,3*mm),
              Paragraph(result.get("description",""), ps("desc")),
              Spacer(1,5*mm),
              HRFlowable(width="100%", thickness=1, color=C_BORDER),
              Spacer(1,4*mm)]

    # ── Top Strengths ────────────────────────────────────────────────────
    story += [section_bar("TOP STRENGTHS", cw), Spacer(1,3*mm),
              Paragraph("   |   ".join(result.get("top_traits",[])),
                        ps("str", fontName="Helvetica-Bold", fontSize=9,
                            textColor=C_BLACK)),
              Spacer(1,2*mm),
              Paragraph("<b>Areas to Improve:</b>   " +
                        ",   ".join(result.get("improve_traits",[])),
                        ps("imp", fontSize=7.5, textColor=C_MID_GRAY)),
              Spacer(1,5*mm)]

    # ── Top Career Matches ───────────────────────────────────────────────
    story += [section_bar("TOP CAREER MATCHES", cw), Spacer(1,2*mm)]
    for i, c in enumerate(result.get("top_careers",[])):
        salary = c.get("salary","").replace("₹","").replace("Rs.","").strip()
        row1 = Table(
            [[Paragraph(f"{i+1}.", ps("n", fontName="Helvetica-Bold", fontSize=9, textColor=C_BLACK)),
              Paragraph(c.get("title",""), ps("ct", fontName="Helvetica-Bold", fontSize=10, textColor=C_BLACK)),
              Paragraph(salary, ps("sal", fontName="Helvetica-Bold", fontSize=9,
                                   textColor=C_GREEN, alignment=TA_RIGHT))]],
            colWidths=[8*mm, cw-8*mm-28*mm, 28*mm]
        )
        row1.setStyle(TableStyle([
            ("VALIGN",(0,0),(-1,-1),"TOP"),
            ("LEFTPADDING",(0,0),(-1,-1),2),
            ("TOPPADDING",(0,0),(-1,-1),0),
            ("BOTTOMPADDING",(0,0),(-1,-1),0),
        ]))
        row2 = Table(
            [[Spacer(10,1), Paragraph(c.get("reason",""), ps("cr", fontSize=8.5, textColor=C_DARK_GRAY))]],
            colWidths=[10*mm, cw-10*mm]
        )
        row2.setStyle(TableStyle([
            ("LEFTPADDING",(0,0),(-1,-1),2),
            ("TOPPADDING",(0,0),(-1,-1),0),
            ("BOTTOMPADDING",(0,0),(-1,-1),2),
        ]))
        bg = C_LIGHT_GRAY if i % 2 == 0 else C_WHITE
        block = Table([[row1],[row2]], colWidths=[cw])
        block.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), bg),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 6),
            ("LINEBELOW",     (0,-1),(-1,-1), 0.4, C_BORDER),
        ]))
        story.append(block)
    story.append(Spacer(1,5*mm))

    # ── Recommended Courses ──────────────────────────────────────────────
    story += [section_bar("RECOMMENDED COURSES", cw), Spacer(1,2*mm)]
    hdr = [["#","Course Name","Platform","Duration","Cost","URL"]]
    rows = hdr + [[str(i+1), c.get("name",""), c.get("platform",""),
                   c.get("duration",""), "Free" if c.get("free") else "Paid",
                   c.get("url","")]
                  for i,c in enumerate(result.get("courses",[]))]
    ct = Table(rows,
               colWidths=[8*mm, 52*mm, 22*mm, 18*mm, 12*mm,
                           cw-8*mm-52*mm-22*mm-18*mm-12*mm],
               repeatRows=1)
    ct.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), C_ACCENT2),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,0), 7.5),
        ("TOPPADDING",    (0,0),(-1,0), 4),
        ("BOTTOMPADDING", (0,0),(-1,0), 4),
        ("FONTNAME",      (0,1),(-1,-1), "Helvetica"),
        ("FONTSIZE",      (0,1),(-1,-1), 8),
        ("TEXTCOLOR",     (0,1),(-1,-1), C_DARK_GRAY),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, C_LIGHT_GRAY]),
        ("TOPPADDING",    (0,1),(-1,-1), 4),
        ("BOTTOMPADDING", (0,1),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 5),
        ("RIGHTPADDING",  (0,0),(-1,-1), 5),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ALIGN",         (4,0),(4,-1), "CENTER"),
        ("TEXTCOLOR",     (4,1),(4,-1), C_GREEN),
        ("FONTNAME",      (4,1),(4,-1), "Helvetica-Bold"),
    ]))
    story += [ct, Spacer(1,5*mm)]

    # ── Skill Gap Analysis ───────────────────────────────────────────────
    story += [section_bar("SKILL GAP ANALYSIS", cw), Spacer(1,2*mm)]
    col = (cw - 4*mm) / 2
    sh = Table([["SKILLS YOU HAVE", "SKILLS TO LEARN"]], colWidths=[col, col])
    sh.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(0,0), HexColor("#D4EDDA")),
        ("BACKGROUND",    (1,0),(1,0), HexColor("#FFF3CD")),
        ("TEXTCOLOR",     (0,0),(0,0), C_GREEN),
        ("TEXTCOLOR",     (1,0),(1,0), C_ORANGE),
        ("FONTNAME",      (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 8),
        ("ALIGN",         (0,0),(-1,-1), "CENTER"),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("GRID",          (0,0),(-1,-1), 0.5, C_BORDER),
    ]))
    story.append(sh)
    have  = result.get("skills_you_have", [])
    learn = result.get("skills_to_learn", [])
    mr    = max(len(have), len(learn))
    sdata = [[Paragraph(("• " + have[i])  if i < len(have)  else "", ps("sk")),
              Paragraph(("• " + learn[i]) if i < len(learn) else "", ps("sk"))]
             for i in range(mr)]
    st = Table(sdata, colWidths=[col, col])
    st.setStyle(TableStyle([
        ("ROWBACKGROUNDS",(0,0),(-1,-1), [colors.white, C_LIGHT_GRAY]),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
    ]))
    story += [st, Spacer(1,5*mm)]

    # ── Learning Roadmap ─────────────────────────────────────────────────
    story += [section_bar("LEARNING ROADMAP", cw), Spacer(1,2*mm)]
    for ph in result.get("roadmap", []):
        tasks = [Paragraph(f"• {t}", ps("bt", fontSize=8.5, textColor=C_DARK_GRAY,
                                        leftIndent=10, leading=13))
                 for t in ph.get("tasks", [])]
        row = Table(
            [[[Paragraph(ph.get("month",""),
                          ps("rm", fontName="Helvetica-Bold", fontSize=9.5,
                              textColor=C_ACCENT, leading=13)),
               Paragraph(ph.get("goal",""),
                          ps("rg", fontName="Helvetica-BoldOblique", fontSize=8.5,
                              textColor=C_DARK_GRAY, leading=12))],
              tasks]],
            colWidths=[45*mm, cw - 45*mm]
        )
        row.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(0,0), HexColor("#EAF0F8")),
            ("BACKGROUND",    (1,0),(1,0), colors.white),
            ("VALIGN",        (0,0),(-1,-1), "TOP"),
            ("LEFTPADDING",   (0,0),(-1,-1), 8),
            ("TOPPADDING",    (0,0),(-1,-1), 6),
            ("BOTTOMPADDING", (0,0),(-1,-1), 6),
            ("LINEAFTER",     (0,0),(0,0), 0.5, C_BORDER),
            ("LINEBELOW",     (0,0),(-1,-1), 0.5, C_BORDER),
        ]))
        story += [KeepTogether(row), Spacer(1,1*mm)]
    story.append(Spacer(1,4*mm))

    # ── Work & Leadership Style ──────────────────────────────────────────
    story += [section_bar("WORK & LEADERSHIP STYLE", cw), Spacer(1,2*mm)]
    wdata = [
        [Paragraph("Team Style",       ps("lk", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("team_style",""),        ps("wt"))],
        [Paragraph("Leadership Style", ps("lk2", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("leadership_style",""),  ps("wt2"))],
        [Paragraph("Ideal Environment",ps("lk3", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("ideal_work_environment",""), ps("wt3"))],
    ]
    wt = Table(wdata, colWidths=[38*mm, cw - 38*mm])
    wt.setStyle(TableStyle([
        ("ROWBACKGROUNDS",(0,0),(-1,-1), [C_LIGHT_GRAY, colors.white]),
        ("TOPPADDING",    (0,0),(-1,-1), 6),
        ("BOTTOMPADDING", (0,0),(-1,-1), 6),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("RIGHTPADDING",  (0,0),(-1,-1), 8),
        ("VALIGN",        (0,0),(-1,-1), "TOP"),
        ("LINEBELOW",     (0,0),(-1,-1), 0.3, C_BORDER),
        ("LINEAFTER",     (0,0),(0,-1), 0.5, C_BORDER),
    ]))
    story += [wt, Spacer(1,5*mm)]

    # ── Famous People ────────────────────────────────────────────────────
    story += [section_bar("FAMOUS PEOPLE WITH YOUR PERSONALITY", cw), Spacer(1,3*mm)]
    fp = result.get("famous_people", [])
    fc = [[Paragraph(n, ps(f"fp{i}", fontName="Helvetica-Bold", fontSize=9,
                           textColor=C_ACCENT, alignment=TA_CENTER)) for i,n in enumerate(fp)]]
    ft = Table(fc, colWidths=[cw/len(fp)]*len(fp))
    ft.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), HexColor("#EAF0F8")),
        ("TOPPADDING",    (0,0),(-1,-1), 8),
        ("BOTTOMPADDING", (0,0),(-1,-1), 8),
        ("GRID",          (0,0),(-1,-1), 0.4, C_BORDER),
    ]))
    story.append(ft)

    # ── Build ────────────────────────────────────────────────────────────
    doc = BaseDocTemplate(
        output_path, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=22*mm, bottomMargin=14*mm,
        title="CareerMind AI – Personality Assessment Report",
        author="CareerMind AI",
    )
    frame   = Frame(MARGIN, 14*mm, PAGE_W-2*MARGIN, PAGE_H-22*mm-14*mm, id="main")
    tmpl    = PageTemplate(id="main", frames=[frame], onPage=draw_header_footer)
    doc.addPageTemplates([tmpl])
    doc.build(story)


# ═════════════════════════════════════════════════════════════════════════
#  SHARE CARD (PNG) GENERATOR  – 1200 × 630 px  (LinkedIn / WhatsApp)
# ═════════════════════════════════════════════════════════════════════════

# ── colour helpers ──────────────────────────────────────────────────────
def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
 
 
# Palette
IMG_NAVY      = rgb("1A3A5C")
IMG_BLUE      = rgb("2E6DA4")
IMG_LIGHT_BLU = rgb("EAF0F8")
IMG_BG        = rgb("FFFFFF")
IMG_GRAY      = rgb("F2F2F2")
IMG_DKGRAY    = rgb("4A4A4A")
IMG_MDGRAY    = rgb("787878")
IMG_BLACK     = rgb("1A1A1A")
IMG_GREEN     = rgb("2D6A4F")
IMG_ORANGE    = rgb("C25B00")
IMG_BORDER    = rgb("CCCCCC")
IMG_PILL_BG   = rgb("1A3A5C")
IMG_ACCENT_G  = rgb("D4EDDA")
IMG_ACCENT_Y  = rgb("FFF3CD")
IMG_WHITE     = (255, 255, 255)
IMG_HEADER_TX = (168, 196, 224)
 
CARD_W, CARD_H = 1200, 780
 
 
# ── font loader ─────────────────────────────────────────────────────────
def load_font(size, bold=False):
    candidates = (
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arialbd.ttf"]
        if bold else
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arial.ttf"]
    )
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()
 
 
# ── drawing helpers ──────────────────────────────────────────────────────
def rect(draw, x, y, w, h, fill, radius=0):
    if radius:
        draw.rounded_rectangle([x, y, x + w, y + h], radius=radius, fill=fill)
    else:
        draw.rectangle([x, y, x + w, y + h], fill=fill)
 
 
def text_w(draw, text, font):
    return int(draw.textlength(text, font=font))
 
 
def section_header(draw, x, y, w, label, font, bg=None):
    """Draws a full-width section label bar; returns new y."""
    bg = bg or IMG_BLUE
    rect(draw, x, y, w, 34, bg)
    draw.text((x + 14, y + 7), label, font=font, fill=C_WHITE)
    return y + 34
 
 
def wrap(draw, text, font, max_w):
    words = text.split()
    lines, line = [], []
    for word in words:
        probe = " ".join(line + [word])
        if draw.textlength(probe, font=font) <= max_w:
            line.append(word)
        else:
            if line:
                lines.append(" ".join(line))
            line = [word]
    if line:
        lines.append(" ".join(line))
    return lines
 
 
# ════════════════════════════════════════════════════════════════════════
#  MAIN CARD GENERATOR
# ════════════════════════════════════════════════════════════════════════
 
def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
 
 
# Palette
IMG_NAVY      = rgb("1A3A5C")
IMG_BLUE      = rgb("2E6DA4")
IMG_LIGHT_BLU = rgb("EAF0F8")
IMG_BG        = rgb("FFFFFF")
IMG_GRAY      = rgb("F2F2F2")
IMG_DKGRAY    = rgb("4A4A4A")
IMG_MDGRAY    = rgb("787878")
IMG_BLACK     = rgb("1A1A1A")
IMG_GREEN     = rgb("2D6A4F")
IMG_ORANGE    = rgb("C25B00")
IMG_BORDER    = rgb("CCCCCC")
IMG_PILL_BG   = rgb("1A3A5C")
IMG_ACCENT_G  = rgb("D4EDDA")
IMG_ACCENT_Y  = rgb("FFF3CD")
IMG_WHITE     = (255, 255, 255)
IMG_HEADER_TX = (168, 196, 224)
 
CARD_W, CARD_H = 1200, 780
 
 
# ── font loader ─────────────────────────────────────────────────────────
def load_font(size, bold=False):
    candidates = (
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arialbd.ttf"]
        if bold else
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arial.ttf"]
    )
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()
 
 
# ── drawing helpers ──────────────────────────────────────────────────────
def rect(draw, x, y, w, h, fill, radius=0):
    if radius:
        draw.rounded_rectangle([x, y, x + w, y + h], radius=radius, fill=fill)
    else:
        draw.rectangle([x, y, x + w, y + h], fill=fill)
 
 
def text_w(draw, text, font):
    return int(draw.textlength(text, font=font))
 
 
def section_header(draw, x, y, w, label, font, bg=None):
    """Draws a full-width section label bar; returns new y."""
    bg = bg or IMG_BLUE
    rect(draw, x, y, w, 34, bg)
    draw.text((x + 14, y + 7), label, font=font, fill=IMG_WHITE)
    return y + 34
 
 
def wrap(draw, text, font, max_w):
    words = text.split()
    lines, line = [], []
    for word in words:
        probe = " ".join(line + [word])
        if draw.textlength(probe, font=font) <= max_w:
            line.append(word)
        else:
            if line:
                lines.append(" ".join(line))
            line = [word]
    if line:
        lines.append(" ".join(line))
    return lines
 
 
# ════════════════════════════════════════════════════════════════════════
#  MAIN CARD GENERATOR
# ════════════════════════════════════════════════════════════════════════
 
def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
 
 
# Palette
IMG_NAVY      = rgb("1A3A5C")
IMG_BLUE      = rgb("2E6DA4")
IMG_LIGHT_BLU = rgb("EAF0F8")
IMG_BG        = rgb("FFFFFF")
IMG_GRAY      = rgb("F2F2F2")
IMG_DKGRAY    = rgb("4A4A4A")
IMG_MDGRAY    = rgb("787878")
IMG_BLACK     = rgb("1A1A1A")
IMG_GREEN     = rgb("2D6A4F")
IMG_ORANGE    = rgb("C25B00")
IMG_BORDER    = rgb("CCCCCC")
IMG_PILL_BG   = rgb("1A3A5C")
IMG_ACCENT_G  = rgb("D4EDDA")
IMG_ACCENT_Y  = rgb("FFF3CD")
IMG_WHITE     = (255, 255, 255)
IMG_HEADER_TX = (168, 196, 224)
 
CARD_W, CARD_H = 1200, 780
 
 
# ── font loader ─────────────────────────────────────────────────────────
def load_font(size, bold=False):
    candidates = (
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arialbd.ttf"]
        if bold else
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arial.ttf"]
    )
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()
 
 
# ── drawing helpers ──────────────────────────────────────────────────────
def rect(draw, x, y, w, h, fill, radius=0):
    if radius:
        draw.rounded_rectangle([x, y, x + w, y + h], radius=radius, fill=fill)
    else:
        draw.rectangle([x, y, x + w, y + h], fill=fill)
 
 
def text_w(draw, text, font):
    return int(draw.textlength(text, font=font))
 
 
def section_header(draw, x, y, w, label, font, bg=None):
    """Draws a full-width section label bar; returns new y."""
    bg = bg or IMG_BLUE
    rect(draw, x, y, w, 34, bg)
    draw.text((x + 14, y + 7), label, font=font, fill=C_WHITE)
    return y + 34
 
 
def wrap(draw, text, font, max_w):
    words = text.split()
    lines, line = [], []
    for word in words:
        probe = " ".join(line + [word])
        if draw.textlength(probe, font=font) <= max_w:
            line.append(word)
        else:
            if line:
                lines.append(" ".join(line))
            line = [word]
    if line:
        lines.append(" ".join(line))
    return lines
 
 
# ════════════════════════════════════════════════════════════════════════
#  MAIN CARD GENERATOR
# ════════════════════════════════════════════════════════════════════════
 
def rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))
 
 
# Palette
IMG_NAVY      = rgb("1A3A5C")
IMG_BLUE      = rgb("2E6DA4")
IMG_LIGHT_BLU = rgb("EAF0F8")
IMG_BG        = rgb("FFFFFF")
IMG_GRAY      = rgb("F2F2F2")
IMG_DKGRAY    = rgb("4A4A4A")
IMG_MDGRAY    = rgb("787878")
IMG_BLACK     = rgb("1A1A1A")
IMG_GREEN     = rgb("2D6A4F")
IMG_ORANGE    = rgb("C25B00")
IMG_BORDER    = rgb("CCCCCC")
IMG_PILL_BG   = rgb("1A3A5C")
IMG_ACCENT_G  = rgb("D4EDDA")
IMG_ACCENT_Y  = rgb("FFF3CD")
IMG_WHITE     = (255, 255, 255)
IMG_HEADER_TX = (168, 196, 224)
 
CARD_W, CARD_H = 1200, 780
 
 
# ── font loader ─────────────────────────────────────────────────────────
def load_font(size, bold=False):
    candidates = (
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arialbd.ttf"]
        if bold else
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arial.ttf"]
    )
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()
 
 
# ── drawing helpers ──────────────────────────────────────────────────────
def rect(draw, x, y, w, h, fill, radius=0):
    if radius:
        draw.rounded_rectangle([x, y, x + w, y + h], radius=radius, fill=fill)
    else:
        draw.rectangle([x, y, x + w, y + h], fill=fill)
 
 
def text_w(draw, text, font):
    return int(draw.textlength(text, font=font))
 
 
def section_header(draw, x, y, w, label, font, bg=None):
    """Draws a full-width section label bar; returns new y."""
    bg = bg or IMG_BLUE
    rect(draw, x, y, w, 34, bg)
    draw.text((x + 14, y + 7), label, font=font, fill=IMG_WHITE)
    return y + 34
 
 
def wrap(draw, text, font, max_w):
    words = text.split()
    lines, line = [], []
    for word in words:
        probe = " ".join(line + [word])
        if draw.textlength(probe, font=font) <= max_w:
            line.append(word)
        else:
            if line:
                lines.append(" ".join(line))
            line = [word]
    if line:
        lines.append(" ".join(line))
    return lines
 
 
# ════════════════════════════════════════════════════════════════════════
#  MAIN CARD GENERATOR
# ════════════════════════════════════════════════════════════════════════
 
def generate_card(result, output_path):
 
    img  = Image.new("RGB", (CARD_W, CARD_H), IMG_BG)
    draw = ImageDraw.Draw(img)
 
    # ── Fonts ──────────────────────────────────────────────────────────
    f_tiny    = load_font(19)
    f_small   = load_font(22)
    f_body    = load_font(26)
    f_medium  = load_font(30)
    f_label   = load_font(19, bold=True)
    f_bold_s  = load_font(24, bold=True)
    f_bold_m  = load_font(30, bold=True)
    f_bold_l  = load_font(38, bold=True)
    f_type    = load_font(82, bold=True)
    f_section = load_font(18, bold=True)
 
    # ── HEADER BAR ─────────────────────────────────────────────────────
    rect(draw, 0, 0, CARD_W, 64, IMG_NAVY)
    draw.text((40, 13),  "CAREERMIND AI",             font=f_bold_s, fill=IMG_WHITE)
    draw.text((40, 39),  "Personality Assessment Report", font=f_small, fill=IMG_HEADER_TX)
    site = "careermind.app"
    site_w = text_w(draw, site, f_small)

    draw.text(
        (CARD_W - 40 - site_w, 32),
        site,
        font=f_small,
        fill=IMG_HEADER_TX
    )
    
    BODY_Y = 64          # content starts here
    FOOTER_H = 46
    BODY_H = CARD_H - BODY_Y - FOOTER_H
 
    # ── LEFT PANEL  (width = 340) ──────────────────────────────────────
    LP_W = 340
    rect(draw, 0, BODY_Y, LP_W, BODY_H, IMG_LIGHT_BLU)
 
    # Personality type code
    p_type = result.get("personality_type", "")
    p_name = result.get("personality_name", "")
 
    ty_w = text_w(draw, p_type, f_type)
    draw.text(((LP_W - ty_w) // 2, BODY_Y + 48), p_type, font=f_type, fill=IMG_NAVY)
 
    # Horizontal rule
    rule_y = BODY_Y + 152
    draw.line([(30, rule_y), (LP_W - 30, rule_y)], fill=IMG_BORDER, width=1)
 
    # Personality name + label
    nm_w = text_w(draw, p_name, f_bold_l)
    draw.text(((LP_W - nm_w) // 2, rule_y + 12), p_name, font=f_bold_l, fill=IMG_BLACK)
 
    lbl = "MBTI Personality Type"
    lbl_w = text_w(draw, lbl, f_small)
    draw.text(((LP_W - lbl_w) // 2, rule_y + 56), lbl, font=f_small, fill=IMG_MDGRAY)
 
    # Rule 2
    rule2_y = rule_y + 90
    draw.line([(30, rule2_y), (LP_W - 30, rule2_y)], fill=IMG_BORDER, width=1)
 
    # "TOP STRENGTHS" label
    ts_lbl = "TOP STRENGTHS"
    ts_lbl_w = text_w(draw, ts_lbl, f_label)
    draw.text(((LP_W - ts_lbl_w) // 2, rule2_y + 12), ts_lbl, font=f_label, fill=IMG_MDGRAY)
 
    # Trait pills – centred, with consistent spacing
    traits = result.get("top_traits", [])[:5]
    pill_y = rule2_y + 44
    PILL_H  = 36
    PILL_PAD_X = 20
    PILL_GAP = 14
 
    for trait in traits:
        tw = text_w(draw, trait, f_bold_s) + PILL_PAD_X * 2
        pill_x = (LP_W - tw) // 2
        rect(draw, pill_x, pill_y, tw, PILL_H, IMG_PILL_BG, radius=5)
        draw.text((LP_W // 2, pill_y + PILL_H // 2), trait,
                  font=f_bold_s, fill=IMG_WHITE, anchor="mm")
        pill_y += PILL_H + PILL_GAP
 
    # ── RIGHT PANEL  ──────────────────────────────────────────────────
    RP_X  = LP_W + 18
    RP_W  = CARD_W - RP_X - 28
    ry    = BODY_Y + 18          # running y inside right panel
 
    # Description (max 3 lines)
    desc_lines = wrap(draw, result.get("description", ""), f_body, RP_W)[:3]
    for line in desc_lines:
        draw.text((RP_X, ry), line, font=f_body, fill=IMG_DKGRAY)
        ry += 34
    ry += 10
 
    # ── Career Matches ────────────────────────────────────────────────
    ry = section_header(draw, RP_X, ry, RP_W, "TOP CAREER MATCHES", f_section, IMG_BLUE)
    ry += 4
 
    careers = result.get("top_careers", [])[:3]
    ROW_H = 44
    for i, c in enumerate(careers):
        title  = c.get("title", "")
        salary = c.get("salary", "").replace("₹", "").replace("Rs.", "").strip()
        bg_col = IMG_GRAY if i % 2 == 0 else IMG_BG
        rect(draw, RP_X, ry, RP_W, ROW_H, bg_col)
        # number
        num = f"{i + 1}."
        draw.text((RP_X + 10, ry + 12), num,    font=f_bold_s, fill=IMG_NAVY)
        # title
        draw.text((RP_X + 42, ry + 12), title,  font=f_bold_m, fill=IMG_BLACK)
        # salary right-aligned
        salary_w = text_w(draw, salary, f_bold_s)
        draw.text(
            (RP_X + RP_W - 10 - salary_w, ry + 12),
            salary,
            font=f_bold_s,
            fill=IMG_GREEN
        )
        # bottom border
        draw.line([(RP_X, ry + ROW_H - 1), (RP_X + RP_W, ry + ROW_H - 1)],
                  fill=IMG_BORDER, width=1)
        ry += ROW_H
    ry += 12
 
    # ── Famous People ─────────────────────────────────────────────────
    ry = section_header(draw, RP_X, ry, RP_W, "FAMOUS PEOPLE WITH YOUR PERSONALITY", f_section, IMG_NAVY)
    ry += 8
 
    famous = result.get("famous_people", [])
    fp_text = "   •   ".join(famous)
    # auto-shrink if too wide
    fp_font = f_bold_m
    while text_w(draw, fp_text, fp_font) > RP_W - 10 and fp_font.size > 18:
        fp_font = load_font(fp_font.size - 2, bold=True)
    draw.text((RP_X, ry), fp_text, font=fp_font, fill=IMG_NAVY)
    ry += fp_font.size + 14
 
    # ── Skill Gap ─────────────────────────────────────────────────────
    COL_GAP = 12
    COL_W   = (RP_W - COL_GAP) // 2
 
    # Header row
    rect(draw, RP_X,              ry, COL_W, 30, IMG_ACCENT_G)
    rect(draw, RP_X + COL_W + COL_GAP, ry, COL_W, 30, IMG_ACCENT_Y)
 
    h_lbl1 = "SKILLS YOU HAVE"
    h_lbl2 = "SKILLS TO LEARN"
    lbl1_w = text_w(draw, h_lbl1, f_label)
    lbl2_w = text_w(draw, h_lbl2, f_label)
    draw.text((RP_X + (COL_W - lbl1_w) // 2, ry + 6),
              h_lbl1, font=f_label, fill=IMG_GREEN)
    draw.text((RP_X + COL_W + COL_GAP + (COL_W - lbl2_w) // 2, ry + 6),
              h_lbl2, font=f_label, fill=IMG_ORANGE)
    ry += 30
 
    have  = result.get("skills_you_have",  [])[:4]
    learn = result.get("skills_to_learn",  [])[:4]
    rows  = max(len(have), len(learn))
    SKILL_H = 32
    for j in range(rows):
        bg_s = IMG_BG if j % 2 == 0 else IMG_GRAY
        rect(draw, RP_X,                    ry, COL_W, SKILL_H, bg_s)
        rect(draw, RP_X + COL_W + COL_GAP, ry, COL_W, SKILL_H, bg_s)
        if j < len(have):
            draw.text((RP_X + 10, ry + 7),
                      f"• {have[j]}", font=f_small, fill=IMG_DKGRAY)
        if j < len(learn):
            draw.text((RP_X + COL_W + COL_GAP + 10, ry + 7),
                      f"• {learn[j]}", font=f_small, fill=IMG_DKGRAY)
        draw.line([(RP_X, ry + SKILL_H - 1),
                   (RP_X + RP_W, ry + SKILL_H - 1)], fill=IMG_BORDER, width=1)
        ry += SKILL_H
 
    # ── FOOTER BAR ────────────────────────────────────────────────────
    footer_y = CARD_H - FOOTER_H
    rect(draw, 0, footer_y, CARD_W, FOOTER_H, IMG_NAVY)
    footer_txt = "Generated by CareerMind AI   |   careermind.app   |   Take your free personality test"
    draw.text((40, footer_y + 14), footer_txt, font=f_small, fill=IMG_HEADER_TX)
 
    try:
        # Create folder automatically
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        img.save(output_path, "PNG")
        print("PNG SAVED SUCCESSFULLY")
        print("PATH:", output_path)

    except Exception as e:
        print("PNG ERROR:")
        print(e)

# ═════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    data        = json.loads(sys.argv[1])
    pdf_path    = sys.argv[2]
    png_path    = sys.argv[3]
    generate_pdf(data, pdf_path)
    generate_card(data, png_path)
    print("OK")