"""
CareerMind AI – Report Generator
Usage:
  python generateReport.py <json_string> <output_pdf> <output_png>
"""

import sys, json, textwrap, os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    BaseDocTemplate, PageTemplate, Frame,
    Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether
)
from reportlab.lib.colors import HexColor
from PIL import Image, ImageDraw, ImageFont

# ── COLOURS ──────────────────────────────────────────────────────────────
C_BLACK      = HexColor("#1A1A1A")
C_DARK_GRAY  = HexColor("#4A4A4A")
C_MID_GRAY   = HexColor("#787878")
C_LIGHT_GRAY = HexColor("#F2F2F2")
C_WHITE      = colors.white
C_ACCENT     = HexColor("#1A3A5C")
C_ACCENT2    = HexColor("#2E6DA4")
C_BORDER     = HexColor("#CCCCCC")
C_GREEN      = HexColor("#2D6A4F")
C_ORANGE     = HexColor("#C25B00")

PAGE_W, PAGE_H = A4
MARGIN = 20 * mm


# ═════════════════════════════════════════════════════════════════════════
#  PDF GENERATOR
# ═════════════════════════════════════════════════════════════════════════

def draw_header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # Header bar
    canvas.setFillColor(C_ACCENT)
    canvas.rect(0, h - 18*mm, w, 18*mm, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.white)
    canvas.drawString(MARGIN, h - 10*mm, "CAREERMIND AI")
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#A8C4E0"))
    canvas.drawString(MARGIN, h - 15*mm, "Personality Assessment Report")
    canvas.drawRightString(w - MARGIN, h - 12.5*mm, "careermind.app")
    # Footer bar
    canvas.setFillColor(C_ACCENT)
    canvas.rect(0, 0, w, 10*mm, fill=1, stroke=0)
    canvas.setFont("Helvetica", 6.5)
    canvas.setFillColor(HexColor("#A8C4E0"))
    canvas.drawCentredString(w/2, 3.5*mm,
        "Generated by CareerMind AI   |   careermind.app   |   Discover your personality, find your career path")
    canvas.setFont("Helvetica-Bold", 7)
    canvas.setFillColor(colors.white)
    canvas.drawRightString(w - MARGIN, 3.5*mm, f"Page {doc.page}")
    canvas.restoreState()


def ps(name, fontName="Helvetica", fontSize=9, textColor=None, leading=None,
       alignment=TA_LEFT, leftIndent=0, bold=False):
    if bold:
        fontName = "Helvetica-Bold"
    if textColor is None:
        textColor = C_DARK_GRAY
    if leading is None:
        leading = fontSize * 1.4
    return ParagraphStyle(name, fontName=fontName, fontSize=fontSize,
                          textColor=textColor, leading=leading,
                          alignment=alignment, leftIndent=leftIndent)


def section_bar(title, cw):
    t = Table([[Paragraph(title, ps("sh", fontName="Helvetica-Bold", fontSize=7,
                                     textColor=colors.white, leading=9))]],
              colWidths=[cw])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), C_ACCENT),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
    ]))
    return t


def generate_pdf(result, output_path):
    cw = PAGE_W - 2*MARGIN
    story = []

    # ── Identity block ──────────────────────────────────────────────────
    id_table = Table(
        [[[Paragraph(result["personality_type"],
                     ps("tc", fontName="Helvetica-Bold", fontSize=38,
                         textColor=C_ACCENT, leading=42))],
          [Spacer(1, 6*mm),
           Paragraph(result["personality_name"],
                     ps("tn", fontName="Helvetica-Bold", fontSize=17,
                         textColor=C_BLACK, leading=22)),
           Paragraph("MBTI Personality Type",
                     ps("tl", fontSize=7.5, textColor=C_MID_GRAY, leading=10))]]],
        colWidths=[45*mm, cw - 45*mm]
    )
    id_table.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), C_LIGHT_GRAY),
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        ("LEFTPADDING",   (0,0),(-1,-1), 10),
        ("TOPPADDING",    (0,0),(-1,-1), 6),
        ("BOTTOMPADDING", (0,0),(-1,-1), 6),
        ("LINEAFTER",     (0,0),(0,0), 1, C_BORDER),
    ]))
    story += [id_table, Spacer(1,3*mm),
              Paragraph(result.get("description",""), ps("desc")),
              Spacer(1,5*mm),
              HRFlowable(width="100%", thickness=1, color=C_BORDER),
              Spacer(1,4*mm)]

    # ── Top Strengths ────────────────────────────────────────────────────
    story += [section_bar("TOP STRENGTHS", cw), Spacer(1,3*mm),
              Paragraph("   |   ".join(result.get("top_traits",[])),
                        ps("str", fontName="Helvetica-Bold", fontSize=9,
                            textColor=C_BLACK)),
              Spacer(1,2*mm),
              Paragraph("<b>Areas to Improve:</b>   " +
                        ",   ".join(result.get("improve_traits",[])),
                        ps("imp", fontSize=7.5, textColor=C_MID_GRAY)),
              Spacer(1,5*mm)]

    # ── Top Career Matches ───────────────────────────────────────────────
    story += [section_bar("TOP CAREER MATCHES", cw), Spacer(1,2*mm)]
    for i, c in enumerate(result.get("top_careers",[])):
        salary = c.get("salary","").replace("₹","").replace("Rs.","").strip()
        row1 = Table(
            [[Paragraph(f"{i+1}.", ps("n", fontName="Helvetica-Bold", fontSize=9, textColor=C_BLACK)),
              Paragraph(c.get("title",""), ps("ct", fontName="Helvetica-Bold", fontSize=10, textColor=C_BLACK)),
              Paragraph(salary, ps("sal", fontName="Helvetica-Bold", fontSize=9,
                                   textColor=C_GREEN, alignment=TA_RIGHT))]],
            colWidths=[8*mm, cw-8*mm-28*mm, 28*mm]
        )
        row1.setStyle(TableStyle([
            ("VALIGN",(0,0),(-1,-1),"TOP"),
            ("LEFTPADDING",(0,0),(-1,-1),2),
            ("TOPPADDING",(0,0),(-1,-1),0),
            ("BOTTOMPADDING",(0,0),(-1,-1),0),
        ]))
        row2 = Table(
            [[Spacer(10,1), Paragraph(c.get("reason",""), ps("cr", fontSize=8.5, textColor=C_DARK_GRAY))]],
            colWidths=[10*mm, cw-10*mm]
        )
        row2.setStyle(TableStyle([
            ("LEFTPADDING",(0,0),(-1,-1),2),
            ("TOPPADDING",(0,0),(-1,-1),0),
            ("BOTTOMPADDING",(0,0),(-1,-1),2),
        ]))
        bg = C_LIGHT_GRAY if i % 2 == 0 else C_WHITE
        block = Table([[row1],[row2]], colWidths=[cw])
        block.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(-1,-1), bg),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 6),
            ("LINEBELOW",     (0,-1),(-1,-1), 0.4, C_BORDER),
        ]))
        story.append(block)
    story.append(Spacer(1,5*mm))

    # ── Recommended Courses ──────────────────────────────────────────────
    story += [section_bar("RECOMMENDED COURSES", cw), Spacer(1,2*mm)]
    hdr = [["#","Course Name","Platform","Duration","Cost","URL"]]
    rows = hdr + [[str(i+1), c.get("name",""), c.get("platform",""),
                   c.get("duration",""), "Free" if c.get("free") else "Paid",
                   c.get("url","")]
                  for i,c in enumerate(result.get("courses",[]))]
    ct = Table(rows,
               colWidths=[8*mm, 52*mm, 22*mm, 18*mm, 12*mm,
                           cw-8*mm-52*mm-22*mm-18*mm-12*mm],
               repeatRows=1)
    ct.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,0), C_ACCENT2),
        ("TEXTCOLOR",     (0,0),(-1,0), colors.white),
        ("FONTNAME",      (0,0),(-1,0), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,0), 7.5),
        ("TOPPADDING",    (0,0),(-1,0), 4),
        ("BOTTOMPADDING", (0,0),(-1,0), 4),
        ("FONTNAME",      (0,1),(-1,-1), "Helvetica"),
        ("FONTSIZE",      (0,1),(-1,-1), 8),
        ("TEXTCOLOR",     (0,1),(-1,-1), C_DARK_GRAY),
        ("ROWBACKGROUNDS",(0,1),(-1,-1), [colors.white, C_LIGHT_GRAY]),
        ("TOPPADDING",    (0,1),(-1,-1), 4),
        ("BOTTOMPADDING", (0,1),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 5),
        ("RIGHTPADDING",  (0,0),(-1,-1), 5),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
        ("ALIGN",         (4,0),(4,-1), "CENTER"),
        ("TEXTCOLOR",     (4,1),(4,-1), C_GREEN),
        ("FONTNAME",      (4,1),(4,-1), "Helvetica-Bold"),
    ]))
    story += [ct, Spacer(1,5*mm)]

    # ── Skill Gap Analysis ───────────────────────────────────────────────
    story += [section_bar("SKILL GAP ANALYSIS", cw), Spacer(1,2*mm)]
    col = (cw - 4*mm) / 2
    sh = Table([["SKILLS YOU HAVE", "SKILLS TO LEARN"]], colWidths=[col, col])
    sh.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(0,0), HexColor("#D4EDDA")),
        ("BACKGROUND",    (1,0),(1,0), HexColor("#FFF3CD")),
        ("TEXTCOLOR",     (0,0),(0,0), C_GREEN),
        ("TEXTCOLOR",     (1,0),(1,0), C_ORANGE),
        ("FONTNAME",      (0,0),(-1,-1), "Helvetica-Bold"),
        ("FONTSIZE",      (0,0),(-1,-1), 8),
        ("ALIGN",         (0,0),(-1,-1), "CENTER"),
        ("TOPPADDING",    (0,0),(-1,-1), 5),
        ("BOTTOMPADDING", (0,0),(-1,-1), 5),
        ("GRID",          (0,0),(-1,-1), 0.5, C_BORDER),
    ]))
    story.append(sh)
    have  = result.get("skills_you_have", [])
    learn = result.get("skills_to_learn", [])
    mr    = max(len(have), len(learn))
    sdata = [[Paragraph(("• " + have[i])  if i < len(have)  else "", ps("sk")),
              Paragraph(("• " + learn[i]) if i < len(learn) else "", ps("sk"))]
             for i in range(mr)]
    st = Table(sdata, colWidths=[col, col])
    st.setStyle(TableStyle([
        ("ROWBACKGROUNDS",(0,0),(-1,-1), [colors.white, C_LIGHT_GRAY]),
        ("TOPPADDING",    (0,0),(-1,-1), 4),
        ("BOTTOMPADDING", (0,0),(-1,-1), 4),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("GRID",          (0,0),(-1,-1), 0.3, C_BORDER),
    ]))
    story += [st, Spacer(1,5*mm)]

    # ── Learning Roadmap ─────────────────────────────────────────────────
    story += [section_bar("LEARNING ROADMAP", cw), Spacer(1,2*mm)]
    for ph in result.get("roadmap", []):
        tasks = [Paragraph(f"• {t}", ps("bt", fontSize=8.5, textColor=C_DARK_GRAY,
                                        leftIndent=10, leading=13))
                 for t in ph.get("tasks", [])]
        row = Table(
            [[[Paragraph(ph.get("month",""),
                          ps("rm", fontName="Helvetica-Bold", fontSize=9.5,
                              textColor=C_ACCENT, leading=13)),
               Paragraph(ph.get("goal",""),
                          ps("rg", fontName="Helvetica-BoldOblique", fontSize=8.5,
                              textColor=C_DARK_GRAY, leading=12))],
              tasks]],
            colWidths=[45*mm, cw - 45*mm]
        )
        row.setStyle(TableStyle([
            ("BACKGROUND",    (0,0),(0,0), HexColor("#EAF0F8")),
            ("BACKGROUND",    (1,0),(1,0), colors.white),
            ("VALIGN",        (0,0),(-1,-1), "TOP"),
            ("LEFTPADDING",   (0,0),(-1,-1), 8),
            ("TOPPADDING",    (0,0),(-1,-1), 6),
            ("BOTTOMPADDING", (0,0),(-1,-1), 6),
            ("LINEAFTER",     (0,0),(0,0), 0.5, C_BORDER),
            ("LINEBELOW",     (0,0),(-1,-1), 0.5, C_BORDER),
        ]))
        story += [KeepTogether(row), Spacer(1,1*mm)]
    story.append(Spacer(1,4*mm))

    # ── Work & Leadership Style ──────────────────────────────────────────
    story += [section_bar("WORK & LEADERSHIP STYLE", cw), Spacer(1,2*mm)]
    wdata = [
        [Paragraph("Team Style",       ps("lk", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("team_style",""),        ps("wt"))],
        [Paragraph("Leadership Style", ps("lk2", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("leadership_style",""),  ps("wt2"))],
        [Paragraph("Ideal Environment",ps("lk3", fontName="Helvetica-Bold", fontSize=8.5, textColor=C_ACCENT2)),
         Paragraph(result.get("ideal_work_environment",""), ps("wt3"))],
    ]
    wt = Table(wdata, colWidths=[38*mm, cw - 38*mm])
    wt.setStyle(TableStyle([
        ("ROWBACKGROUNDS",(0,0),(-1,-1), [C_LIGHT_GRAY, colors.white]),
        ("TOPPADDING",    (0,0),(-1,-1), 6),
        ("BOTTOMPADDING", (0,0),(-1,-1), 6),
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("RIGHTPADDING",  (0,0),(-1,-1), 8),
        ("VALIGN",        (0,0),(-1,-1), "TOP"),
        ("LINEBELOW",     (0,0),(-1,-1), 0.3, C_BORDER),
        ("LINEAFTER",     (0,0),(0,-1), 0.5, C_BORDER),
    ]))
    story += [wt, Spacer(1,5*mm)]

    # ── Famous People ────────────────────────────────────────────────────
    story += [section_bar("FAMOUS PEOPLE WITH YOUR PERSONALITY", cw), Spacer(1,3*mm)]
    fp = result.get("famous_people", [])
    fc = [[Paragraph(n, ps(f"fp{i}", fontName="Helvetica-Bold", fontSize=9,
                           textColor=C_ACCENT, alignment=TA_CENTER)) for i,n in enumerate(fp)]]
    ft = Table(fc, colWidths=[cw/len(fp)]*len(fp))
    ft.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), HexColor("#EAF0F8")),
        ("TOPPADDING",    (0,0),(-1,-1), 8),
        ("BOTTOMPADDING", (0,0),(-1,-1), 8),
        ("GRID",          (0,0),(-1,-1), 0.4, C_BORDER),
    ]))
    story.append(ft)

    # ── Build ────────────────────────────────────────────────────────────
    doc = BaseDocTemplate(
        output_path, pagesize=A4,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=22*mm, bottomMargin=14*mm,
        title="CareerMind AI – Personality Assessment Report",
        author="CareerMind AI",
    )
    frame   = Frame(MARGIN, 14*mm, PAGE_W-2*MARGIN, PAGE_H-22*mm-14*mm, id="main")
    tmpl    = PageTemplate(id="main", frames=[frame], onPage=draw_header_footer)
    doc.addPageTemplates([tmpl])
    doc.build(story)


# ═════════════════════════════════════════════════════════════════════════
#  SHARE CARD (PNG) GENERATOR  – 1200 × 630 px  (LinkedIn / WhatsApp)
# ═════════════════════════════════════════════════════════════════════════

# PIL colour helpers
def rgb(hex_str):
    hex_str = hex_str.lstrip("#")
    return tuple(int(hex_str[i:i+2], 16) for i in (0, 2, 4))

CARD_W, CARD_H = 1200, 680

C_CARD_BG      = rgb("FFFFFF")
C_CARD_HEADER  = rgb("1A3A5C")
C_CARD_NAVY    = rgb("1A3A5C")
C_CARD_BLUE    = rgb("2E6DA4")
C_CARD_GRAY    = rgb("F2F2F2")
C_CARD_DKGRAY  = rgb("4A4A4A")
C_CARD_MDGRAY  = rgb("787878")
C_CARD_BLACK   = rgb("1A1A1A")
C_CARD_GREEN   = rgb("2D6A4F")
C_CARD_BORDER  = rgb("CCCCCC")
C_CARD_LIGHT   = rgb("EAF0F8")


def load_font(size, bold=False):
    """Try to load a system font; fall back to PIL default."""
    candidates = (
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arialbd.ttf"]
        if bold else
        ["/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
         "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
         "/System/Library/Fonts/Helvetica.ttc",
         "C:/Windows/Fonts/arial.ttf"]
    )
    for path in candidates:
        if os.path.exists(path):
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()


def draw_rect(draw, x, y, w, h, fill, radius=0):
    if radius:
        draw.rounded_rectangle([x, y, x+w, y+h], radius=radius, fill=fill)
    else:
        draw.rectangle([x, y, x+w, y+h], fill=fill)


def wrap_text(text, font, max_width, draw):
    words = text.split()
    lines, line = [], []
    for word in words:
        test = " ".join(line + [word])
        if draw.textlength(test, font=font) <= max_width:
            line.append(word)
        else:
            if line:
                lines.append(" ".join(line))
            line = [word]
    if line:
        lines.append(" ".join(line))
    return lines


def generate_card(result, output_path):
    img  = Image.new("RGB", (CARD_W, CARD_H), C_CARD_BG)
    draw = ImageDraw.Draw(img)

    # ── Fonts ─────────────────────────────────────────────────────────────
    f_tiny   = load_font(20)
    f_small  = load_font(24)
    f_body   = load_font(28)
    f_medium = load_font(32)
    f_large  = load_font(42)
    f_xlarge = load_font(80, bold=True)
    f_title  = load_font(44, bold=True)
    f_bold_s = load_font(26, bold=True)
    f_bold_m = load_font(32, bold=True)
    f_bold_l = load_font(40, bold=True)
    f_label  = load_font(20, bold=True)

    # ── Header bar ────────────────────────────────────────────────────────
    draw_rect(draw, 0, 0, CARD_W, 70, C_CARD_HEADER)
    draw.text((40, 16), "CAREERMIND AI", font=f_bold_s, fill=(255,255,255))
    draw.text((40, 42), "Personality Assessment Report", font=f_small, fill=(168,196,224))
    draw.text((CARD_W - 40, 36), "careermind.app",
              font=f_small, fill=(168,196,224), anchor="rm")

    # ── Identity block (left panel) ──────────────────────────────────────
    draw_rect(draw, 0, 70, 400, CARD_H - 70 - 50, C_CARD_LIGHT)

    p_type = result.get("personality_type","")
    p_name = result.get("personality_name","")

    # Big type code
    draw.text((200, 130), p_type, font=f_xlarge, fill=C_CARD_NAVY, anchor="mm")

    # Divider under type
    draw.line([(40, 200), (360, 200)], fill=C_CARD_BORDER, width=1)

    # Name
    draw.text((200, 230), p_name, font=f_bold_l, fill=C_CARD_BLACK, anchor="mm")
    draw.text((200, 274), "MBTI Personality Type", font=f_small,
              fill=C_CARD_MDGRAY, anchor="mm")

    # Divider
    draw.line([(40, 300), (360, 300)], fill=C_CARD_BORDER, width=1)

    # Top traits (stacked pills)
    draw.text((200, 330), "TOP STRENGTHS", font=f_label, fill=C_CARD_MDGRAY, anchor="mm")
    traits = result.get("top_traits", [])[:5]
    ty = 360
    for trait in traits:
        tw = int(draw.textlength(trait, font=f_bold_s)) + 30
        tx = 200 - tw // 2
        draw_rect(draw, tx, ty, tw, 36, C_CARD_HEADER, radius=4)
        draw.text((200, ty + 18), trait, font=f_bold_s, fill=(255,255,255), anchor="mm")
        ty += 46

    # ── Main content (right panel) ────────────────────────────────────────
    RX = 420  # right panel x start
    RW = CARD_W - RX - 40  # right panel width

    # Description
    desc = result.get("description","")
    desc_font = f_body
    desc_lines = wrap_text(desc, desc_font, RW, draw)[:3]
    dy = 90
    for line in desc_lines:
        draw.text((RX, dy), line, font=desc_font, fill=C_CARD_DKGRAY)
        dy += 38
    dy += 10

    # ── Career matches section ────────────────────────────────────────────
    draw_rect(draw, RX, dy, RW, 36, C_CARD_BLUE)
    draw.text((RX + 14, dy + 8), "TOP CAREER MATCHES",
              font=f_label, fill=(255,255,255))
    dy += 44

    careers = result.get("top_careers",[])[:3]
    for i, c in enumerate(careers):
        title  = c.get("title","")
        salary = c.get("salary","").replace("₹","").replace("Rs.","").strip()
        bg_col = C_CARD_GRAY if i % 2 == 0 else C_CARD_BG
        draw_rect(draw, RX, dy, RW, 46, bg_col)
        num_w  = int(draw.textlength(f"{i+1}.", font=f_bold_s)) + 8
        draw.text((RX + 12, dy + 13), f"{i+1}.", font=f_bold_s, fill=C_CARD_NAVY)
        draw.text((RX + 12 + num_w, dy + 13), title, font=f_bold_m, fill=C_CARD_BLACK)
        draw.text((RX + RW - 10, dy + 13), salary,
                  font=f_bold_s, fill=C_CARD_GREEN, anchor="ra")
        dy += 48
    dy += 14

    # ── Famous people section ─────────────────────────────────────────────
    draw_rect(draw, RX, dy, RW, 36, C_CARD_NAVY)
    draw.text((RX + 14, dy + 8), "FAMOUS PEOPLE WITH YOUR PERSONALITY",
              font=f_label, fill=(255,255,255))
    dy += 44

    famous = result.get("famous_people",[])
    famous_text = "   •   ".join(famous)
    draw.text((RX, dy), famous_text, font=f_bold_m, fill=C_CARD_NAVY)
    dy += 46

    # ── Skill summary ─────────────────────────────────────────────────────
    half = (RW - 16) // 2
    draw_rect(draw, RX,          dy, half, 34, rgb("D4EDDA"))
    draw_rect(draw, RX+half+16,  dy, half, 34, rgb("FFF3CD"))
    draw.text((RX + half//2, dy + 17), "SKILLS YOU HAVE",
              font=f_label, fill=C_CARD_GREEN, anchor="mm")
    draw.text((RX + half + 16 + half//2, dy + 17), "SKILLS TO LEARN",
              font=f_label, fill=rgb("C25B00"), anchor="mm")
    dy += 38

    have  = result.get("skills_you_have",[])[:3]
    learn = result.get("skills_to_learn",[])[:3]
    skill_rows = max(len(have), len(learn))
    for j in range(skill_rows):
        bg_s = C_CARD_BG if j % 2 == 0 else C_CARD_GRAY
        draw_rect(draw, RX,         dy, half, 34, bg_s)
        draw_rect(draw, RX+half+16, dy, half, 34, bg_s)
        if j < len(have):
            draw.text((RX+10, dy+9), f"• {have[j]}", font=f_small, fill=C_CARD_DKGRAY)
        if j < len(learn):
            draw.text((RX+half+26, dy+9), f"• {learn[j]}", font=f_small, fill=C_CARD_DKGRAY)
        dy += 34

    # ── Footer bar ────────────────────────────────────────────────────────
    draw_rect(draw, 0, CARD_H - 50, CARD_W, 50, C_CARD_HEADER)
    draw.text((40, CARD_H - 50 + 15),
              "Generated by CareerMind AI   |   careermind.app   |   Take your free personality test",
              font=f_small, fill=(168,196,224))

    img.save(output_path, "PNG", quality=95)


# ═════════════════════════════════════════════════════════════════════════
#  ENTRY POINT
# ═════════════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    data        = json.loads(sys.argv[1])
    pdf_path    = sys.argv[2]
    png_path    = sys.argv[3]
    generate_pdf(data, pdf_path)
    generate_card(data, png_path)
    print("OK")